version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: wanderoo_php
        volumes:
            - .:/app
        working_dir: /app
        ports:
            - "8000:8000"
        environment:
            REDIS_URL: redis://redis:6379
        command: php -S 0.0.0.0:8000 -t public
        depends_on:
            - redis

    redis:
        image: redis:7-alpine
        container_name: wanderoo_redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    db:
        image: mysql:8.0
        container_name: wanderoo_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wanderoo
            MYSQL_USER: wanderoo_user
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    redis_data:
    db_data:
