version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: wanderoo_app
        volumes:
            - .:/app
        working_dir: /app
        ports:
            - "8000:8000"
        command: php -S 0.0.0.0:8000 -t public

#    database:
#        image: postgres:${POSTGRES_VERSION:-16}-alpine
#        environment:
#            POSTGRES_DB: ${POSTGRES_DB:-app}
#            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#            POSTGRES_USER: ${POSTGRES_USER:-app}
#        healthcheck:
#            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
#            timeout: 5s
#            retries: 5
#            start_period: 60s
#        volumes:
#            - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

volumes:
  database_data:
